
profiles:
  now: local

server:
  shutdown: graceful
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
  tomcat:
    uri-encoding: UTF-8
  port: 9999

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: 2022pmds-backend-user
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: ENC(HvYSlQq94IULCxDzbuAHjfkwkB8TNqHJiKCohKNb8zWm/1nfDv6WnSlZdbk3Fz0nu2j9Smw4EfI=)
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ENC(2hosz5Mw10FD8O6XlN/EHw==)
    password: ENC(GWuh8WXhq3TvVw92GRnPr5o11QPIrwhV)
    hikari:
      connection-timeout: 50000
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
#########################################################
#### Actuator
#########################################################
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: never
    shutdown:
      enabled: true
    caches:
      enabled: false

info:
  organization:
    name: thj0309
  contact:
    email: thj0309@hotmail.com

#########################################################
#### logging
#########################################################
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    #org.springframework.cloud.sleuth: TRACE
    org.springframework.cache: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.jpa: TRACE
    #org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    com.zaxxer.hikari: DEBUG

#########################################################
#### swagger
#########################################################
swagger:
  base:
    path: com.backend


#########################################################
#### Encrypt & Decrypt
#########################################################
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: A421080gsm


#########################################################
#### Eureka client
#########################################################
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

token:
  expiration_time: 86400000
  secret: user_token