
server:
  port: 9999


spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:log4jdbc:mariadb://localhost:3306/2022pmds?characterEncoding=UTF-8
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: pmds
    password: pmds
    hikari:
      connection-timeout: 50000
  jpa:
    generate-ddl: true
    hibernate:
      # create / create-drop / update / validate / none
      ddl_auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
#    properties:
#      hibernate:
#        validator:
#          apply_to_ddl: true
#        format_sql: true
#        default_batch_fetch_size: 1000
#        cache:
#          use_second_level_cache: true
#          region:
#            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
#        javax:
#          persistence:
#            sharedCache:
#              mode: ENABLE_SELECTIVE
#########################################################
#### Actuator
#########################################################
management:
  endpoints:
    web:
      base-path: /health
      path-mapping:
        health: _check
  endpoint:
    health:
      show-details: never

#########################################################
#### logging
#########################################################
logging:
  level:
    root: INFO
    tving.gaia: DEBUG
    org.springframework: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    #org.springframework.cloud.sleuth: TRACE
    org.springframework.cache: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.jpa: TRACE
    #org.hibernate.type: TRACE
    org.hibernate.type.descriptor.sql: TRACE
    com.zaxxer.hikari: DEBUG
